Snake game first PR
FraserGreenroyd/SwedeGaming pull request #2
Opened 2018-02-14 01:05 UTC by edforsberg

@FraserGreenroyd Please have a look at the code when you've got time to spare. There's probably lots and lots of errors but stuff is happening.

2018-02-17 10:06 UTC, FraserGreenroyd requested changes
This is good work Erik so far, I'm really pleased to see the progress on the snake and the discussions that have been had around it that have enhanced the classes that we've been developing.

I've made some minor comments on the code, see comments and feel free to question it if it doesn't make sense or you feel my comment is wrong :+1:

2018-02-17 10:06 UTC, FraserGreenroyd commented on public/UID.js
> +    // I generate the UID from two parts here
Minor comment - can this code comment be on one line please

2018-02-17 10:06 UTC, FraserGreenroyd commented on public/engine.js
> +class engine
Which type of engine is this? Class name should reflect the type of engine, if I remember rightly this is a game engine?

2018-02-17 10:06 UTC, FraserGreenroyd commented on public/engine.js
> +	{}
Empty object?

2018-02-17 10:06 UTC, FraserGreenroyd commented on public/engine.js
> +}
Overall I feel this engine class needs a lot of work - ideally we should be using Angular to handle a lot of our events for us, including the draw and key press.

I'm happy to merge this into the main code as an interim to complete the pull request (when other changes are made), but we need to have a strong think about the best way for engine implementation.

2018-02-17 10:06 UTC, FraserGreenroyd commented on public/snake.js
> +	{}
Empty object?

2018-02-17 10:06 UTC, FraserGreenroyd commented on public/snake.js
> +	var dirrEnum = {"up":1, "down":2, "left":3, "right":4}
I would recommend changing this to remove the speech marks on the keys. See below example.

`var dirrEnum = {
    up : 1,
    down : 2,
    left : 3,
    right : 4,
};`

2018-02-17 10:06 UTC, FraserGreenroyd commented on public/snake.js
> +	]; //all coordinates occupied by the snake
Implementation question - are we storing all the points the snake occupies, or are we storing the points where the snake has turned (think polyline points in Rhino or Grasshopper)?

2018-02-17 10:06 UTC, FraserGreenroyd commented on public/snake.js
> +
Has consideration been given to using a `switch` statement instead of if-elses? I'm happy with if-elses but wondering if consideration had been given?

2018-02-17 10:06 UTC, FraserGreenroyd commented on public/snake.js
> +		if (currDir == dirrEnum.up) {newMouthPos = {mouthPosition[0], mouthPosition[1]+1}}
If going up should the y position not be losing a point to go closer to zero? Assuming (0,0) is top left, going 'up' for the snake would be y - 1 not y + 1?

2018-02-17 10:06 UTC, FraserGreenroyd commented on public/snake.js
> +			else if (currDir == dirrEnum.down){newMouthPos = {mouthPosition[0], mouthPosition[1]-1}}
See previous comment regarding y position.

2018-02-17 10:06 UTC, FraserGreenroyd commented on public/snake.js
> +			if (head[0]< 0 || head[0]>engine.xSize || head[1]< 0 || head[1]>engine.ySize) {engine.gameOver = true;}
Have we considered the possibility of wrapping the snake so it can go through walls?

Also, any checks done to see if the snake intersects with itself?

2018-02-17 10:06 UTC, FraserGreenroyd commented on public/snakeFood.js
> +		{}
Guess what? Empty object?

2018-02-17 10:06 UTC, FraserGreenroyd commented on public/snakeFood.js
> +			if(rand > 9){bonusFactor = 4}
Missing semi-colon.

2018-02-17 10:06 UTC, FraserGreenroyd commented on public/snakeFood.js
> +			int rand = Math.getRandomInt(0,10)
Missing semi-colon.

2018-02-17 10:06 UTC, FraserGreenroyd commented on public/snakeFood.js
> +				else if (rand > 7) {bonusFactor = 2}
Missing semi-colon.

2018-02-17 10:06 UTC, FraserGreenroyd commented on public/snakeFood.js
> +			while(isInsnake)
Missing curly brackets {} to scope the while statement - this while loop will run infinitely.

2018-02-17 10:06 UTC, FraserGreenroyd commented on public/snake.js
> +
Also, a severe lack of semi-colons within the curly brackets.

2018-02-19 19:29 UTC, edforsberg commented on public/snake.js
> +	]; //all coordinates occupied by the snake
We are only going to store the positions that the snake currently occupies at any given moment.

2018-02-19 19:41 UTC, FraserGreenroyd commented on public/snake.js
> +	]; //all coordinates occupied by the snake
![image](https://user-images.githubusercontent.com/18049174/36394479-5cf60c36-15ac-11e8-962c-1a54a4224462.png)

See image above. Are we going to store the points that make up the entire snake (i.e. 55 pixels) or just the three points that define the snake curve from which we can calculate the interim positions (i.e. 3 pixels)?

2018-02-19 20:31 UTC, edforsberg commented on public/snake.js
> +	]; //all coordinates occupied by the snake
That makes NO sense. I'll implement it. :)

2018-04-24 13:12 UTC, merged